SFPD/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('departments.urls')),
    path('profiles/', include('profiles.urls')),
    path('news/', include('news.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

departments/urls.py
from django.urls import path
from . import views

app_name = 'departments'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('police_academy/', views.pa_view, name='pa_detail'),
    path('cpd/', views.cpd_view, name='cpd_detail'),
    path('swat/', views.swat_view, name='swat_detail'),
    path('seb/', views.seb_view, name='seb_detail'),
    path('db/', views.db_view, name='db_detail'),
    path('about/', views.about_view, name='about'),
    path('faq/', views.faq_view, name='faq'),
    path('faq/', views.faq_view, name='faq'),
    path('hall_of_fame/', views.hall_fame, name='hall_of_fame'),
    path('thank_board/', views.thank_board, name='thank_board'),
    path('police-academy/', views.police_academy_view, name='police_academy_view'),
    path('department-staff/', views.edit_department_staff, name='edit_department_staff'),
    path('subscribe/', views.SubscribeView.as_view(), name='subscribe'),
    path('unsubscribe/<str:token>/', views.unsubscribe_view, name='unsubscribe'),
    path('change-history/', views.change_history_list, name='change_history_list'),
]

templates/include/change_history_list.html
{% load static %}
{% include 'base.html' %}
<!DOCTYPE html>

<html class="wide wow-animation" lang="en">
<head>
    <title>История изменений</title>
    <style>
        .section-title {
            font-size: 2rem;
            font-weight: bold;
            margin-bottom: 1rem;
        }

        .change-log {
            border: 1px solid #ddd;
            padding: 1rem;
            border-radius: 8px;
            background-color: #f9f9f9;
        }


        .change-entry {
            padding: 1rem;
            border-bottom: 1px solid #ddd;
        }

        .change-entry:last-child {
            border-bottom: none;
        }

        .date-right {
            text-align: right;
        }

    </style>
</head>
<body>
<div class="preloader">
    <div class="preloader-body">
        <div class="loader">
            <img class="preloader-ico" src="{% static 'images/history.png' %}" alt="">
        </div>
        <H5>Загрузка...</H5>
    </div>
</div>
<div class="page">
    {% include 'include/navbar.html' %}
    <div class="rd-navbar-bg novi-background bg-image"
         style="background-image: url('{% static 'images/bg-navbar.png' %}')"></div>
    <section class="breadcrumbs-custom bg-image novi-background bg-primary">
        <div class="container">
            <ul class="breadcrumbs-custom-path">
                <li><a href="{% url 'departments:home' %}">Главная</a></li>
                <li class="active">История изменений</li>
            </ul>
        </div>
    </section>
    <section class="section section-md">
        <div class="container">
            <div class="row row-50">
                <div class="col-12">
                    <h2 class="section-title">История изменений</h2>
                    <h6>Здесь вы можете отслеживать все изменения, исправления багов и доработки на сайте.</h6>

                    <div class="change-log">
                        {% for change in changes %}
                            <div class="change-entry mb-4">
                                <div class="box-icon-3 unit flex-column flex-lg-row">
                                    <div class="unit-left">
                                        <div class="icon novi-icon random-icon"></div>
                                    </div>
                                    <div class="unit-body">
                                        <h5 class="title">{{ change.title }}</h5>
                                        <p class="text">{{ change.description }}</p>
                                        <p class="text date-right">{{ change.created_at|date:"Y-m-d" }}</p>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>

    {% include 'include/footer.html' %}

    <div class="snackbars" id="form-output-global"></div>
    <script src="{% static 'js/core.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
    {% include 'include/notifications.html' %}
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            var icons = [
                "mercury-icon-gears",
                "mercury-icon-gear",
                "mercury-icon-lightbulb-gears",
                "mercury-icon-tools"
            ];

            var iconElements = document.querySelectorAll('.random-icon');
            iconElements.forEach(function (element) {
                var randomIcon = icons[Math.floor(Math.random() * icons.length)];
                element.classList.add(randomIcon);
            });
        });
    </script>
</div>
</body>
</html>

templates/include/footer.html
{% load static %}
<footer class="section footer-classic">
    <div class="footer-inner-1">
        <div class="container">
            <div class="row row-40">
                <div class="col-md-5 col-lg-3">
                    <h5>Наши контакты</h5>
                    <ul class="contact-list font-weight-bold">
                        <li>
                            <div class="unit unit-spacing-xs">
                                <div class="unit-left">
                                    <div class="icon icon-sm icon-primary novi-icon">
                                        <img src="{% static 'images/discord.svg' %}" alt="Discord Icon" width="16px"
                                             height="16px">
                                    </div>
                                </div>
                                <div class="unit-body">
                                    <a href="https://discord.gg/ddnRXcQJCV" target="_blank">Discord</a>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="unit unit-spacing-xs">
                                <div class="unit-body"><a href="https://evolve-rp.su/index.php?forums/46/"
                                                          target="_blank"><i class="fa fa-newspaper-o"
                                                                             aria-hidden="true"></i> Форум</a>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="unit unit-spacing-xs">
                                <div class="unit-body">
                                    <a href="https://vk.com/saintlouis_sfpd" target="_blank"><i class="fa fa-vk"
                                                                                                aria-hidden="true"></i>
                                        Официальное сообщество<br>департамента</a>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="unit unit-spacing-xs">
                                <div class="unit-body">
                                    <ul class="list-0">
                                        <i class="fa fa-clock-o" aria-hidden="true"></i> Рабочее время департамента
                                        <li>Будни: 9:00–21:00</li>
                                        <li>Выходные: 10:00–20:00</li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="col-md-6 col-lg-5">
                    <h5>Ссылки</h5>
                    <div class="row row-5 justify-content-between">
                        <div class="col-sm-6">
                            <ul class="font-weight-bold">
                                <li><a href="{% url 'departments:home' %}"><i
                                        class="fas fa-home" style="margin-right: 2px;"></i>Главная</a></li>
                                <li><a href="{% url 'news_list' %}"><i
                                        class="fas fa-newspaper" style="margin-right: 2px;"></i>Новости</a></li>
                                <li><a href="{% url 'departments:about' %}"><i
                                        class="fas fa-book" style="margin-right: 2px;"></i>О департаменте</a></li>
                                <li><a href="{% url 'departments:faq' %}"><i
                                        class="fas fa-question-circle" style="margin-right: 2px;"></i> FAQ</a></li>
                                {#                                <li><a href="{% url 'departments:hall_of_fame' %}">Доска почета</a></li>#}
                                <li><a href="{% url 'departments:thank_board' %}"><i
                                        class="fas fa-desktop"></i> Благодарственная доска</a></li>
                                <li><a href="{% url 'profile_list' %}"><i
                                        class="fas fa-users"></i> Список пользователей</a></li>
                            </ul>
                        </div>
                        <div class="col-sm-4 col-lg-6 col-xxl-5">
                            <ul class="font-weight-bold">
                                <li><a href="{% url 'departments:pa_detail' %}"><i
                                        class="fas fa-graduation-cap"></i> Police Academy</a></li>
                                <li><a href="{% url 'departments:cpd_detail' %}"><i
                                        class="fas fa-car"></i> CPD</a></li>
                                <li><a href="{% url 'departments:db_detail' %}"><i
                                        class="fas fa-user-secret"></i> Detective Bureau</a></li>
                                <li><a href="{% url 'departments:swat_detail' %}"><i
                                        class="fas fa-hand-peace-o"></i> SWAT</a></li>
                                <li><a href="{% url 'departments:seb_detail' %}"><i
                                        class="fas fa-fighter-jet"></i> SEB</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-12 col-lg-4">
                    <h5>Поддержка</h5>
                    {% include 'include/supports.html' %}
                </div>
            </div>
        </div>
    </div>
    <div class="footer-inner-2">
        <div class="container">
            <p class="rights"><span>&copy;&nbsp;</span><span class="copyright-year"> </span> San-Fierro Police
                Department. Все права защищены.
                Developer by <a href="https://vk.com/lazarev312" target="_blank">Dimentii Lazarev</a></p>
        </div>
    </div>
</footer>

templates/include/notifications.html
<style>
    .toast-container {
        position: fixed;
        bottom: 1rem;
        right: 1rem;
        z-index: 1055;
        display: flex;
        flex-direction: column;
        gap: 0.5rem;
        max-width: 90%; /* Ограничиваем максимальную ширину для небольших экранов */
    }

    .toast {
        position: relative;
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        padding: 0.75rem 1rem;
        background-color: rgba(0, 107, 218, 0.95);
        color: white;
        border-radius: 0.25rem;
        box-shadow: 0 0.25rem 0.75rem rgba(0, 0, 0, 0.1);
        opacity: 0;
        transition: opacity 0.3s ease-in-out;
    }

    .toast.show {
        opacity: 1;
    }

    .toast.hide {
        opacity: 0;
    }

    .toast-header {
        width: 100%;
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 0.5rem;
        border-bottom: 1px solid rgba(255, 255, 255, 0.3);
        padding-bottom: 0.5rem;
    }

    .toast-progress {
        width: 100%;
        height: 4px;
        background: linear-gradient(to left, #ff8c00, #ff4500);
        transition: width 10s linear;
        margin-bottom: 0.5rem;
    }

    .toast-body {
        padding-top: 0.5rem;
        font-size: 0.9rem;
        line-height: 1.4;
    }

    .close {
        background: none;
        border: none;
        color: white;
        font-size: 1.2rem;
        cursor: pointer;
    }

    .close:hover {
        color: #ff8c00;
    }

    @media (max-width: 600px) {
        .toast-container {
            right: 0.5rem;
            bottom: 0.5rem;
            max-width: 100%;
            padding: 0 0.5rem;
        }

        .toast {
            width: 100%;
            border-radius: 0.25rem;
            box-shadow: none;
        }

        .toast-body {
            font-size: 0.8rem;
        }

        .toast-header strong {
            font-size: 1rem;
        }

        .close {
            font-size: 1rem;
        }
    }
</style>

{% if messages %}
    <div class="toast-container">
        {% for message in messages %}
            {% if message.tags == 'success' %}
                <div class="toast" role="alert">
                    <div class="toast-header">
                        <strong>Оповещение:</strong>
                        <button type="button" class="close" aria-label="Close" onclick="closeToast(this)">&times;
                        </button>
                    </div>
                    <div class="toast-progress"></div>
                    <div class="toast-body">
                        {{ message|safe }}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endif %}

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const toasts = document.querySelectorAll('.toast');

        toasts.forEach((toast, index) => {
            setTimeout(() => {
                toast.classList.add('show');
                const progressBar = toast.querySelector('.toast-progress');
                progressBar.style.width = '0%';
            }, index * 500);

            setTimeout(() => {
                toast.classList.remove('show');
                toast.classList.add('hide');
            }, 10500);

            setTimeout(() => {
                toast.remove();
            }, 11000);
        });
    });

    function closeToast(button) {
        const toast = button.closest('.toast');
        toast.classList.remove('show');
        toast.classList.add('hide');
        setTimeout(() => {
            toast.remove();
        }, 500);
    }
</script>

templates/include/supports.html
<style>
    .modal-dialog-custom {
        display: flex;
        align-items: center;
        justify-content: center;
        min-height: calc(100vh - 1rem);
    }

    .modal-content-custom {
        background-color: #fff;
        border: 1px solid rgba(0, 0, 0, 0.2);
        border-radius: 0.3rem;
    }

    .modal-header-custom {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 1rem;
        border-bottom: 1px solid #dee2e6;
        border-top-left-radius: 0.3rem;
        border-top-right-radius: 0.3rem;
    }

    .modal-title {
        margin-bottom: 0;
        line-height: 1.5;
    }

    .close {
        padding: 0.75rem;
        margin: -0.75rem -0.75rem -0.75rem auto;
    }

    .close span {
        position: relative;
        display: inline-block;
        width: 1.5em;
        height: 1.5em;
        background-color: #acb7be;
        border-radius: 50%;
        text-align: center;
        line-height: 1.5em;
        font-size: 1.25em;
        cursor: pointer;
    }

    .close span:hover {
        background-color: #e9ecef;
    }

    .modal-body-custom {
        position: relative;
        flex: 1 1 auto;
        padding: 1rem;
    }
</style>
<button type="button" class="btn button-size-1 button-block button-primary" data-toggle="modal"
        data-target="#supportModal" style="margin-top: 10px"><i class="fa fa-handshake-o" aria-hidden="true"></i>
    Форма поддержки
</button>

<div class="modal fade" id="supportModal" tabindex="-1" aria-labelledby="supportModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-custom">
        <div class="modal-content modal-content-custom">
            <div class="modal-header modal-header-custom">
                <h5 class="modal-title" id="supportModalLabel">Поддержка</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body modal-body-custom">
                <form method="post" action="{% url 'support' %}" id="supportForm">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            {{ support_form.name }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ support_form.email }}
                        </div>
                    </div>
                    <div class="form-group">
                        {{ support_form.message }}
                    </div>
                    <button type="submit" class="btn button-size-1 button-block button-primary"><i
                            class="fa fa-paper-plane" aria-hidden="true"></i> Отправить
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<script>
    $(document).ready(function () {
        $('#supportForm').on('submit', function (event) {
            let isValid = true;
            $(this).find('input[required], textarea[required]').each(function () {
                if ($(this).val() === '') {
                    isValid = false;
                    $(this).addClass('is-invalid');
                } else {
                    $(this).removeClass('is-invalid');
                }
            });
            if (!isValid) {
                event.preventDefault();
                alert('Пожалуйста, заполните все обязательные поля.');
            }
        });

        $('#supportForm').on('submit', function () {
            if ($(this).find('input.is-invalid, textarea.is-invalid').length === 0) {
                $('#supportModal').modal('hide');
            }
        });
    });
</script>